from collections.abc import Iterator
from typing import Any, Union

from torch import Generator, Tensor

OutputTensors = Union[Tensor, list[Tensor], tuple[Tensor, ...]]

def graph_pool_handle() -> int: ...
def get_graph_ptr(graph: CUDAGraph) -> int: ...
def set_allocation_region(base: int, size: int) -> None: ...
def stop_allocation_region() -> None: ...
def resume_allocation_region() -> None: ...
def set_pack_fatbins_on_exit(enabled: bool) -> None: ...
def pack_fatbins_to_folder(folder_path: str) -> None: ...
def load_cuda_modules_and_libraries(archive_dir: str) -> None: ...
def preallocate_cublas_workspaces() -> None: ...

class KernelNodeMetadata:
    num_params: int
    offset_and_sizes: list[tuple[int, int]]
    blockDimX: int
    blockDimY: int
    blockDimZ: int
    gridDimX: int
    gridDimY: int
    gridDimZ: int
    func: int
    kern: int
    ctx: int
    sharedMemBytes: int
    extraSize: int
    argBufferSize: int
    func_name: str

class MemcpyUpdateInfo:
    memcpy_index: int

    def __init__(self) -> None: ...
    def __init__(self, memcpy_index: int) -> None: ...
    def set_srcDevice(self, srcDevice: int) -> None: ...
    def set_dstDevice(self, dstDevice: int) -> None: ...
    def set_srcHost(self, srcHost: int) -> None: ...
    def set_dstHost(self, dstHost: int) -> None: ...
    def set_srcArray(self, srcArray: int) -> None: ...
    def set_dstArray(self, dstArray: int) -> None: ...
    def set_srcXInBytes(self, srcXInBytes: int) -> None: ...
    def set_srcY(self, srcY: int) -> None: ...
    def set_srcZ(self, srcZ: int) -> None: ...
    def set_srcLOD(self, srcLOD: int) -> None: ...
    def set_srcMemoryType(self, srcMemoryType: int) -> None: ...
    def set_dstXInBytes(self, dstXInBytes: int) -> None: ...
    def set_dstY(self, dstY: int) -> None: ...
    def set_dstZ(self, dstZ: int) -> None: ...
    def set_dstLOD(self, dstLOD: int) -> None: ...
    def set_dstMemoryType(self, dstMemoryType: int) -> None: ...
    def set_WidthInBytes(self, WidthInBytes: int) -> None: ...
    def set_Height(self, Height: int) -> None: ...
    def set_Depth(self, Depth: int) -> None: ...
    def set_srcPitch(self, srcPitch: int) -> None: ...
    def set_srcHeight(self, srcHeight: int) -> None: ...
    def set_dstPitch(self, dstPitch: int) -> None: ...
    def set_dstHeight(self, dstHeight: int) -> None: ...

class MemsetUpdateInfo:
    memset_index: int

    def __init__(self) -> None: ...
    def __init__(self, memset_index: int) -> None: ...
    def set_dst(self, dst: int) -> None: ...
    def set_elementSize(self, elementSize: int) -> None: ...
    def set_height(self, height: int) -> None: ...
    def set_pitch(self, pitch: int) -> None: ...
    def set_value(self, value: int) -> None: ...
    def set_width(self, width: int) -> None: ...

class KernelUpdateInfo:
    kernel_index: int

    def __init__(self) -> None: ...
    def __init__(self, kernel_index: int) -> None: ...
    def set_extra(self, extra_config: int) -> None: ...
    def set_kernelParams(self, params: int, metadata: KernelNodeMetadata) -> None: ...
    def add_param_update(
        self, index: int, value_ptr: int, metadata: KernelNodeMetadata
    ) -> None: ...
    def set_blockDim(self, x: int, y: int, z: int) -> None: ...
    def set_gridDim(self, x: int, y: int, z: int) -> None: ...
    def set_func(self, func: int) -> None: ...
    def set_kern(self, kern: int) -> None: ...
    def set_sharedMemBytes(self, bytes: int) -> None: ...

class MemcpyUpdateInfoList:
    def __init__(self) -> None: ...
    def append(self, update_info: MemcpyUpdateInfo) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, i: int) -> MemcpyUpdateInfo: ...
    def __iter__(self) -> Iterator[MemcpyUpdateInfo]: ...
    def __repr__(self) -> str: ...

class MemsetUpdateInfoList:
    def __init__(self) -> None: ...
    def append(self, update_info: MemsetUpdateInfo) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, i: int) -> MemsetUpdateInfo: ...
    def __iter__(self) -> Iterator[MemsetUpdateInfo]: ...
    def __repr__(self) -> str: ...

class KernelUpdateInfoList:
    def __init__(self) -> None: ...
    def append(self, update_info: KernelUpdateInfo) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, i: int) -> KernelUpdateInfo: ...
    def __iter__(self) -> Iterator[KernelUpdateInfo]: ...
    def __repr__(self) -> str: ...

class CUDAGraph:
    def __init__(self, keep_graph: bool = False) -> None: ...
    def capture_begin(self, pool: tuple[int, int] | None, capture_error_mode: str) -> None: ...
    def capture_end(self) -> None: ...
    def register_generator_state(self, generator: Generator) -> None: ...
    def replay(self) -> None: ...
    def reset(self) -> None: ...
    def pool(self) -> Any: ...
    def debug_dump(self) -> None: ...
    def debug_dump(self, debug_path: str) -> None: ...
    def enable_debug_mode(self) -> None: ...
    def raw_cuda_graph(self) -> int: ...
    def save(self, json_path: str, output_tensors: OutputTensors | None = None) -> None: ...
    @staticmethod
    def load(
        json_path: str, pool: tuple[int, int] | None = None
    ) -> tuple[CUDAGraph, OutputTensors | None]: ...
